### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by vsego** [samskivert/chromewheel#1]
The World sorely needs the zoom (mis)function to go away, so I installed extension from Chrome Web Store and force-reloaded a few pages, but the Ctrl+Wheel still zooms in/out. Tested on Google Chrome Version 57.0.2987.133 (64-bit) on Linux.

**Comment by samskivert** [comment]
Works for me? I haven't tested it on Linux but it would be strange if it didn't work there but did on a Mac (which is what I normally use). I'll try it on Linux tomorrow and see what I can figure out.

**Comment by vsego** [comment]
I tried it at home, on Fedora, with Chrome Version 62.0.3202.62, and it worked like a charm, so it might be Chrome version. I'll check if I can upgrade at work (CentOS, so a bit slower on updates).

**Comment by vsego** [comment]
The upgrade didn't help, but something else did. I had No MouseWheel Zoom extension ( https://chrome.google.com/webstore/detail/no-mousewheel-zoom/ckhlfagjncfmdieecfekjbpnnaekhlhd ) installed before and, even though I disabled it, the two seem to have been conflicting. Uninstalling that one solved the problem.
Btw, it seems to scroll about 1.5 pages instead of just one.
